# Use the official .NET SDK image for listening to dotnet commands
FROM mcr.microsoft.com/dotnet/sdk:9.0

# Set the working directory
WORKDIR /app

# Copy the project files
COPY . .

# Keep the container running
CMD ["sleep", "infinity"]