FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

ARG CONFIGURATION

WORKDIR /source

# Copy csproj and restore as distinct layers
COPY ./*.csproj .
RUN dotnet restore

# copy and publish app and libraries
COPY . .
RUN dotnet publish \
    --no-restore \
    -c ${CONFIGURATION} \
    -o /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS server

WORKDIR /app

EXPOSE 8080

COPY --from=build /app .

# Deploy the latest build (executable file)
ENTRYPOINT ["dotnet", "app.dll"]